name: iris
description: A developer friendly back-end framework built with Dart
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.22.1
dependencies:
  meta: ^1.8.0
