name: iris
description: A developer friendly back-end framework built with Dart
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  meta: ^1.8.0
